[project]
name = "word2pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gooey>=1.0.8.1",
    "pandas>=2.2.3",
    "pywin32>=310",
]
