[project]
name = "pyg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame>=2.6.1",
    "requests>=2.25.0",
    "pillow>=8.0.0",
]
